version: '3'

services:
  fastrivia:
    image: nginx:latest
    container_name: fastrivia
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=fastrivia.danielarroyo.dev
      - LETSENCRYPT_HOST=fastrivia.danielarroyo.dev
      - LETSENCRYPT_EMAIL=darroyo083@gmail.com
    volumes:
      - .:/usr/share/nginx/html:ro
      # Descomenta esto si necesitas Nginx personalizado
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
    name: nginx-proxy
